version: "3.8"

networks:
  public:
    driver: bridge
  private:
    ipam:
      driver: default
      config:
        - subnet: 172.28.2.0/24


volumes:
  postgresql:
  postgresql_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_data:
  artifactory_data:


services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - public
      - private

  database:
    image: toastyboii/sonarqube-postgres
    networks:
      - private
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - ./postgres.env

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    networks:
      - private
    ports:
      - "8080:8080"
      - "50000:50000"
    env_file:
      - jenkins.env

  jenkins-agent:
    image: toastyboii/jenkins-agent
    networks:
      - private
    env_file:
      - jenkins-agent.env

  artifactory:
    image: toastyboii/artifactory
    networks:
      - private
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    env_file:
      - artifactory.env
    ports:
      - "8081:8081"
      - "8082:8082"

  sonarqube:
    image: sonarqube:community
    depends_on:
      - database
    networks:
      - private
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    env_file:
      - sonarqube-jdbc.env
      - sonarqube.env
    ports:
      - "9000:9000"
